version: '3.7'
services:
  rest-db:
    container_name: rest-db
    image: postgres
    restart: always
    ports:
      - '5436:5436'
    volumes:
      - ./docker/pddata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_ROOT_PASSWORD: db_pass
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
    networks:
      - rest-db
  rest-php:
    container_name: rest-php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/:cached
    depends_on:
      - rest-db
    networks:
      - rest-db
      - rest-php
  nginx:
    container_name: rest-nginx
    build: docker/nginx
    ports:
      - "88:88"
    depends_on:
      - rest-php
    networks:
      - rest-php
    volumes:
      - ./:/var/www/:cached
      - ./docker/logs/nginx-back:/var/log/nginx:cached

volumes:
  fias_symfony_database:
networks:
  rest-db:
  rest-php:
